#!/usr/bin/env python3
"""
generate-bulk-load-sql.py — generate a Virtuoso isql bulk-load script from a source folder.

Modes:
  dir (default): ld_dir + rdf_loader_run — one named graph for the whole folder;
                 every RDF format + gzip/bzip2 handled natively by Virtuoso.
  per-file:      one named graph per file (Turtle family: .ttl/.nt/.trig) via
                 TTLP_MT, with optional prefix preamble and CLEAR-before-load.

Usage:
  python3 generate-bulk-load-sql.py --source-dir /path/to/rdf --graph https://g/ --pattern '*.ttl'
  python3 generate-bulk-load-sql.py --source-dir /path/to/rdf --mode per-file --preamble --clear
"""
import argparse, glob, os, re, sys
from collections import Counter

DECL = re.compile(r'@prefix\s+(\w*):\s*<([^>]+)>\s*\.')

def expand_patterns(formats):
    ext = {"ttl": "*.ttl", "nt": "*.nt", "nq": "*.nq", "trig": "*.trig",
           "rdf": "*.rdf", "xml": "*.rdf", "jsonld": "*.jsonld", "json": "*.jsonld"}
    out = []
    for f in formats.split(","):
        f = f.strip().lower()
        out.append(ext.get(f, f"*.{f}"))
    return out

def build_preamble(files):
    by = {}
    for f in files:
        try:
            txt = open(f, encoding="utf-8", errors="replace").read()
        except OSError:
            continue
        for m in DECL.finditer(txt):
            by.setdefault(m.group(1), Counter()).update([m.group(2)])
    parts = []
    for name in sorted(by):
        iri = by[name].most_common(1)[0][0]
        if name == "okf" and iri.startswith("okf-"):
            continue
        parts.append(f"@prefix {name}: <{iri}> .")
    curated = {"owl":"http://www.w3.org/2002/07/owl#","cert":"http://www.w3.org/ns/auth/cert#",
      "oplcert":"http://www.openlinksw.com/schemas/cert#","prov":"http://www.w3.org/ns/prov#",
      "rdf":"http://www.w3.org/1999/02/22-rdf-syntax-ns#","rdfs":"http://www.w3.org/2000/01/rdf-schema#",
      "foaf":"http://xmlns.com/foaf/0.1/","skos":"http://www.w3.org/2004/02/skos/core#",
      "event":"http://purl.org/NET/c4dm/event.owl#","opal":"https://www.openlinksw.com/ontology/opal/",
      "dbr":"http://dbpedia.org/resource/","dbo":"http://dbpedia.org/ontology/",
      "wd":"http://www.wikidata.org/entity/","xsd":"http://www.w3.org/2001/XMLSchema#",
      "schema":"http://schema.org/","acl":"http://www.w3.org/ns/auth/acl#",
      "xlink":"http://www.w3.org/1999/xlink","atom":"http://www.w3.org/2005/Atom",
      "sioc":"http://rdfs.org/sioc/ns#","dct":"http://purl.org/dc/terms/","dcterms":"http://purl.org/dc/terms/"}
    for n, iri in sorted(curated.items()):
        if n not in by:
            parts.append(f"@prefix {n}: <{iri}> .")
    return "\n".join(parts) + "\n\n"

def main():
    ap = argparse.ArgumentParser(description="Generate a Virtuoso isql bulk-load script from a source folder")
    ap.add_argument("--source-dir", required=True, help="folder with RDF files (server-visible path)")
    ap.add_argument("--graph", default="urn:dav:/DAV/home/kidehen/bulk-load/", help="target graph IRI (dir mode)")
    ap.add_argument("--pattern", default="*.*", help="ld_dir pattern")
    ap.add_argument("--formats", help="comma list of formats (ttl,nt,nq,trig,rdf,jsonld) -> patterns")
    ap.add_argument("--mode", choices=["dir", "per-file"], default="dir")
    ap.add_argument("--graph-base", default="urn:dav:/DAV/home/kidehen/bulk-load/", help="per-file graph IRI prefix")
    ap.add_argument("--preamble", action="store_true", help="per-file: prepend prefix union preamble")
    ap.add_argument("--clear", action="store_true", help="CLEAR GRAPH before load (idempotent re-runs)")
    ap.add_argument("--out", default="bulk-load.sql")
    ap.add_argument("--dry-run", action="store_true")
    a = ap.parse_args()

    src = a.source_dir.rstrip("/")
    if not os.path.isdir(src):
        print(f"ERROR: --source-dir not a directory: {src}", file=sys.stderr); sys.exit(1)
    patterns = expand_patterns(a.formats) if a.formats else [a.pattern]

    sql = [f"-- bulk-load.sql (generated by generate-bulk-load-sql.py)",
           f"-- source: {src} | mode: {a.mode} | graph: {a.graph}",
           "-- run:  isql 1111 dba <dba-password> -f bulk-load.sql", ""]

    if a.mode == "dir":
        if a.clear:
            sql += [f"SPARQL CLEAR GRAPH <{a.graph}>;", ""]
        for p in patterns:
            sql.append(f"ld_dir ('{src}', '{p}', '{a.graph}');")
        sql += ["", "rdf_loader_run ();"]
    else:
        files = []
        for p in patterns:
            files += sorted(glob.glob(os.path.join(src, p)))
        files = sorted(set(files))
        if not files:
            print(f"ERROR: no files match {patterns} in {src}", file=sys.stderr); sys.exit(1)
        preamble = build_preamble(files) if a.preamble else ""
        for f in files:
            rel = os.path.relpath(f, src).replace(os.sep, "/")
            g = a.graph_base.rstrip("/") + "/" + rel
            if a.clear:
                sql.append(f"SPARQL CLEAR GRAPH <{g}>;")
            body = f"('{preamble}' || file_to_string_output ('{f}')" if a.preamble else f"(file_to_string_output ('{f}')"
            sql.append(f"DB.DBA.TTLP_MT {body}, '{g}', '{g}', 255);")
            sql.append("")
        sql.append(f"-- {len(files)} file(s) queued")

    sql += ["", "-- monitor: rows with ll_state <> 2 are pending or errored (see ll_error)",
            "select * from db.dba.load_list where ll_state <> 2;",
            "", "-- verify: per-graph triple counts",
            "SPARQL SELECT ?g (COUNT(*) AS ?t) WHERE { GRAPH ?g { ?s ?p ?o } } GROUP BY ?g;"]
    script = "\n".join(sql)
    if a.dry_run:
        print(script)
    else:
        with open(a.out, "w", encoding="utf-8") as fh:
            fh.write(script + "\n")
        print(f"WROTE {a.out}")

if __name__ == "__main__":
    main()
