#!/usr/bin/env python3
"""
Load the routing graph into a Virtuoso named graph.

Writes an idempotent isql script (CLEAR GRAPH, then DB.DBA.TTLP_MT of the
Turtle file) that the operator runs with their own dba credential. The script
never contains a password.

Usage:
  python3 scripts/load_graph.py --out "$TMPDIR/load-routing-graph.sql"
  isql 1111 dba <dba-password> < "$TMPDIR/load-routing-graph.sql"

Options:
  --ttl    Turtle file (default: references/routing-graph.ttl)
  --graph  target named graph IRI (default: urn:llmr:routing-graph)
  --out    output .sql path (default: print to stdout)
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REFS = os.path.join(os.path.dirname(HERE), "references")


def build_sql(ttl_path, graph):
    # The Turtle is embedded as a string literal: Virtuoso's DirsAllowed rules
    # often refuse file_to_string_output() for paths outside its data directories.
    if "'" in graph:
        sys.exit("ERROR: quote characters in the graph IRI are not supported")
    with open(ttl_path, encoding="utf-8") as fh:
        body = fh.read().replace("'", "''")
    return "\n".join([
        "-- routing-graph load (generated by scripts/load_graph.py)",
        f"SPARQL CLEAR GRAPH <{graph}>;",
        f"DB.DBA.TTLP_MT ('{body}', '{graph}', '{graph}', 255);",
        "",
    ])


def main():
    ap = argparse.ArgumentParser(description="Generate the isql load script for the routing graph")
    ap.add_argument("--ttl", default=os.path.join(REFS, "routing-graph.ttl"))
    ap.add_argument("--graph", default="urn:llmr:routing-graph")
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    ttl = os.path.abspath(args.ttl)
    if not os.path.exists(ttl):
        sys.exit(f"ERROR: {ttl} not found; run scripts/build_routing_graph.py first")
    sql = build_sql(ttl, args.graph)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(sql)
        print(f"wrote {args.out} (graph {args.graph})")
    else:
        sys.stdout.write(sql)


if __name__ == "__main__":
    main()
