-- Generated from /tmp/openlink-html-dav-category-summary.tsv
-- Purpose: apply content-derived schema:category WebDAV custom properties
-- Target: https://www.openlinksw.com/DAV/www2.openlinksw.com/data/html/
-- Run as a Virtuoso SQL user that can update DAV properties, e.g. DBA via isql.
-- Uses the built-in dba user password hash; no WebDAV password is embedded here.

USE DB;

DROP TABLE DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE;

CREATE TABLE DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (
  PATH VARCHAR(2048) NOT NULL,
  CATEGORY LONG VARCHAR NOT NULL
);

INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2016-07-22_What-is-DBpedia--and-why-is-it-important--d306b5324f90.html', 'DBpedia & Public Data Spaces; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2018-08-04_What-is-a-SPARQL-Endpoint--and-why-is-it-important--b3c9e6a20a8b.html', 'SPARQL & Querying; Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2018-11-20_What-is-a-Virtuoso-SPARQL-Endpoint--and-why-is-it-important--5244df738a3e.html', 'SPARQL & Querying; Virtuoso Platform; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2019-04-11_What-is-Small-Data--and-why-is-it-Important--fbf5f267884.html', 'Database, SQL & PostgreSQL; Semantic Web, RDF & Ontologies; Virtuoso Platform; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2019-06-11_What-is-the-Linked-Open-Data-Cloud--and-why-is-it-important--1901a7cb7b1f.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; DBpedia & Public Data Spaces; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2026-07-17-a2a-client-skill-demo-guide.html', 'OPAL & Agentic AI; Presentation, Infographic & Visual Explanation; Identity, Security & Privacy; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2026-practical-data-community-state-of-data-engineering-gemini-2.html', 'Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; SPARQL & Querying; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/2026-practical-data-community-state-of-data-engineering-gemini.html', 'SPARQL & Querying; Database, SQL & PostgreSQL; Semantic Web, RDF & Ontologies; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/7-agi-sins-infographic-gemini-25.html', 'Analytics, Data Engineering & ERA; Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/7-agi-sins-infographic-gpt-41.html', 'Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; AI Engineering & LLMs; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/7-agi-sins-infographic-grok4.html', 'Analytics, Data Engineering & ERA; Semantic Web, RDF & Ontologies; AI Engineering & LLMs; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/Sponger-Meta-Cartridge-Graph-Meta-Cartridge-Graph.html', 'OpenLink Technical Content');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/Sponger_LinkedDataGenOptions_2018_v3tjt.html', 'Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/WWW-Original-Proposal-and-Linked-Data-4.html', 'Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/WWW-Original-Proposal-and-Linked-Data.html', 'Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/aaron-levie-enterprise-ai-agent-issues-semantic-web-virtuoso-claude_sonnet_5-1.html', 'Semantic Web, RDF & Ontologies; OPAL & Agentic AI; Virtuoso Platform; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-3rd-party-substack-mcp-server-gemini.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; OPAL & Agentic AI; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-agent-web-from-arix-paper-gemini.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-approvia-gemini-2.html', 'Analytics, Data Engineering & ERA; AI Engineering & LLMs; OPAL & Agentic AI; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-dbpedia-2025-06-aws-ami.html', 'Virtuoso Platform; SPARQL & Querying; DBpedia & Public Data Spaces; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-dbpedia-2025-06-azure-ami.html', 'Virtuoso Platform; Knowledge Graphs & Linked Data; DBpedia & Public Data Spaces; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-dbpedia-2025-06.html', 'DBpedia & Public Data Spaces; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-era-knowledge-graph.html', 'Analytics, Data Engineering & ERA; AI Engineering & LLMs; Knowledge Graphs & Linked Data; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-learn2earn-ng-gemini.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-mpesa-claude-1.html', 'Identity, Security & Privacy; Knowledge Graphs & Linked Data; OPAL & Agentic AI; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-openlink-mult-tier-offers.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Identity, Security & Privacy; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-virtuoso-features-detailed.html', 'Virtuoso Platform; Knowledge Graphs & Linked Data; Database, SQL & PostgreSQL; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-virtuoso-graph-analytics-2.html', 'Analytics, Data Engineering & ERA; SPARQL & Querying; Virtuoso Platform; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-virtuoso-graph-analytics.html', 'Analytics, Data Engineering & ERA; SPARQL & Querying; Virtuoso Platform; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/about-wikidata-truthy-2025-11.html', 'DBpedia & Public Data Spaces; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/adia-sowho-article-infographic.html', 'Presentation, Infographic & Visual Explanation; OPAL & Agentic AI; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/ai-price-wars-infographic-1.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/ai-roles-visual-lpg-variant.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/ai-roles-visual.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/ai-value-capture-response-claude_sonnet_5-1.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/anthropic-ai-tools-landscape-html-infographic.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/anthropic-glasswing-infographic-claude-cowork.html', 'Analytics, Data Engineering & ERA; AI Engineering & LLMs; Identity, Security & Privacy; Cloud Storage & S3; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/apple-knowledge-graph-manifestation-3.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/apple-knowledge-graph-manifestation.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/bessemer-ventures-ai-2025-report-claude.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Analytics, Data Engineering & ERA; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/briefcase-det-folders-claude.html', 'WebDAV, ODS & Collaboration; Identity, Security & Privacy; Cloud Storage & S3; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/briefcase-det-folders.html', 'WebDAV, ODS & Collaboration; Identity, Security & Privacy; Cloud Storage & S3; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/building-a-knowledge-using-virtuoso-developers-guide.html', 'Virtuoso Platform; Semantic Web, RDF & Ontologies; SPARQL & Querying; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/building-a-knowledge-using-virtuoso.html', 'Virtuoso Platform; Semantic Web, RDF & Ontologies; SPARQL & Querying; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/buy-and-sell-side-advertising-overview-claude.html', 'Analytics, Data Engineering & ERA; Identity, Security & Privacy; Knowledge Graphs & Linked Data; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/buy-and-sell-side-advertising-overview-gemini.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/chowdeck-vs-jumia-gemini.html', 'Analytics, Data Engineering & ERA; AI Engineering & LLMs; OPAL & Agentic AI; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/christopher_nolan_films.html', 'DBpedia & Public Data Spaces; Semantic Web, RDF & Ontologies; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/christopher_nolan_films_wikidata.html', 'DBpedia & Public Data Spaces; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/claude-code-howto-from-twitter-via-grok-gemini.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Presentation, Infographic & Visual Explanation; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/claude-cowork-guide-infographic.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/claude-managed-agents-infographic.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/claude-virtuoso-support-agent-skills-generated-northwind-knowledge-graph.html', 'Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/comprehension-debt-infographic.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/covid-19-knowedge-graph.html', 'OpenLink Technical Content');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/dan-brickley-rdf-validation-claude.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; Data Virtualization & Integration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/data-silos-problem-claude-1.html', 'Data Virtualization & Integration; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/data-silos-problem-gemini.html', 'Data Virtualization & Integration; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/dbms-independence-markmap.html', 'Data Virtualization & Integration; Presentation, Infographic & Visual Explanation; Database, SQL & PostgreSQL');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/did-craigslist-kill-newspapers-infographic-claude.html', 'Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/dotnet-mcp-infographic-gemini.html', 'AI Engineering & LLMs; Database, SQL & PostgreSQL; Virtuoso Platform; Data Virtualization & Integration; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/elad-gill-ai-market-overview.html', 'Analytics, Data Engineering & ERA; Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/english-alphabet-visualized.html', 'OpenLink Technical Content');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/enterprise-data-harmonization-registry.html', 'Data Virtualization & Integration; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/enterprise-data-harmonization.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Data Virtualization & Integration; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/era-analytics-infographic-via-claude.html', 'Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; AI Engineering & LLMs; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/eupo-cellar-opal-presentation-2.html', 'Analytics, Data Engineering & ERA; SPARQL & Querying; Presentation, Infographic & Visual Explanation; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/eupo-cellar-opal-presentation.html', 'Analytics, Data Engineering & ERA; SPARQL & Querying; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/experience-is-now-a-tax-infographic.html', 'Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/from-chaos-to-order-via-knowledge-graphs.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; AI Engineering & LLMs; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gemini-3-rdf-visualization-demo.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gemini-3-rdf-visualization-kg-as-books-business.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Virtuoso Platform; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/geminicli-subagents-infographic.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gennaro-cuofano-on-ai-productivity-gemini.html', 'Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; OPAL & Agentic AI; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gpt5-overview-simon-wilson-infographic-claude.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gpt5-overview-simon-wilson-infographic-gemini.html', 'AI Engineering & LLMs; Presentation, Infographic & Visual Explanation; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gpt5-overview-simon-wilson-infographic-gpt5-1.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Presentation, Infographic & Visual Explanation; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gpt5-overview-simon-wilson-infographic-gpt5-chat-1.html', 'Presentation, Infographic & Visual Explanation; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gpt5-overview-simon-wilson-infographic-gpt5-chat-2.html', 'Presentation, Infographic & Visual Explanation; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gpt5-overview-simon-wilson-infographic-gpt5-chat.html', 'Presentation, Infographic & Visual Explanation; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/gpt5-overview-simon-wilson-infographic-gpt5.html', 'AI Engineering & LLMs; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/how-i-use-genai-by-claude.html', 'AI Engineering & LLMs; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/how-i-use-genai-by-gemini.html', 'AI Engineering & LLMs; Presentation, Infographic & Visual Explanation; Analytics, Data Engineering & ERA; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/http-signatures-infographic.html', 'Presentation, Infographic & Visual Explanation; Analytics, Data Engineering & ERA; Identity, Security & Privacy; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/hypertext-journey.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/ikea-data-divide-article.html', 'Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/ire-fde-ontology-roles-claude_sonnet46-1.html', 'Semantic Web, RDF & Ontologies; OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/jdbc-mcp-infographic-gemini.html', 'Database, SQL & PostgreSQL; AI Engineering & LLMs; Data Virtualization & Integration; Virtuoso Platform; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/knowledge-graph-explorer.html', 'Knowledge Graphs & Linked Data; SPARQL & Querying; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/knowledge-graph-manifestation-turtle-jsonld.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/lpg2rdf-guide.html', 'Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation; Database, SQL & PostgreSQL; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/lpg2rdf-most-prolific-directors-dashboard-claude-original.html', 'Database, SQL & PostgreSQL; AI Engineering & LLMs; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/lpg2rdf-most-prolific-directors-sparql-dashboard.html', 'Database, SQL & PostgreSQL; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/mckinsey-ai-kg-infographic-via-claude.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/mcp-installation-guide-claude-5.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Identity, Security & Privacy; Virtuoso Platform; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/model-context-protocol-benefits-vdibia-post.html', 'AI Engineering & LLMs; Identity, Security & Privacy; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/mustafa-suleyman-essay-seemingly-conscious-ai-gemini.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/mvc-revisited-in-age-of-ai-via-opal-claude-2.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/nigeria-and-fraud-misrepresentation-2.html', 'Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/nigerian-fashion-industry-gemini.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/northwind-dashboard-rdf-views-claude-3.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-enterprise-for-windows-infographic.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-enterprise-installation-guide-linux.html', 'Database, SQL & PostgreSQL; Data Virtualization & Integration; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-enterprise-installation-guide-windows.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-infographic.html', 'Database, SQL & PostgreSQL; Data Virtualization & Integration; Analytics, Data Engineering & ERA; Virtuoso Platform; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-lite-installation-guide-linux.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-lite-installation-guide-macos.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-lite-installation-guide-windows.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-jdbc-bridge-windows-infographic.html', 'Database, SQL & PostgreSQL; Data Virtualization & Integration; Presentation, Infographic & Visual Explanation; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-mcp-infographic-gemini.html', 'AI Engineering & LLMs; Data Virtualization & Integration; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-odbc-bridge-enterprise-installation-guide-linux.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Identity, Security & Privacy; OPAL & Agentic AI; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-odbc-bridge-enterprise-installation-guide-windows.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-odbc-bridge-installation-guide-windows.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-odbc-bridge-lite-installation-guide-windows.html', 'Data Virtualization & Integration; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-sqlserver-lite-installation-guide-linux.html', 'Database, SQL & PostgreSQL; Data Virtualization & Integration; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-sqlserver-lite-installation-guide-macos.html', 'Database, SQL & PostgreSQL; Data Virtualization & Integration; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/odbc-sqlserver-lite-installation-guide-windows.html', 'Database, SQL & PostgreSQL; Data Virtualization & Integration; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/ods-home-page.html', 'WebDAV, ODS & Collaboration; Database, SQL & PostgreSQL; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-agent-dbpedia-spike-lee-demo-1.html', 'Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; Semantic Web, RDF & Ontologies; Identity, Security & Privacy; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-architecture-revision-3.drawio.html', 'OPAL & Agentic AI; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-architecture.html', 'OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-functions-openapi-docs-from-yaml-gemini-3.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-installation-aws-cloud-guide.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Identity, Security & Privacy; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-installation-azure-cloud-guide.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Identity, Security & Privacy; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-installation-google-cloud-guide.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Identity, Security & Privacy; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-installation-guide-last.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Identity, Security & Privacy; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-installation-guide.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Identity, Security & Privacy; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-mcp-installation-guide.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Identity, Security & Privacy; Virtuoso Platform; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-offers-overview.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-openapi-docs-from-yaml-gemini-2.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-openapi-docs-from-yaml-gemini-3.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-openapi-docs-from-yaml-gemini.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-openapi-functions-docs-from-yaml-gemini.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-presentation-2025-06-19.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Data Virtualization & Integration; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-presentation-2025-06-20.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Data Virtualization & Integration; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-presentation-2025-07-30.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Data Virtualization & Integration; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-services-offers-claude-1.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-services-offers-claude.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-services-offers-gemini-1.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-services-offers-gemini.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-apis-developer-journey-gemini.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-assistants-apis-developer-journey-gemini.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-apis-developer-journey-gemini.html', 'Analytics, Data Engineering & ERA; OPAL & Agentic AI; AI Engineering & LLMs; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-1.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-10.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-10a.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-16.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; WebDAV, ODS & Collaboration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-17.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; WebDAV, ODS & Collaboration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-19.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; WebDAV, ODS & Collaboration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-2.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-3.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-5.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-9.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini-claude-fixed-1.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; WebDAV, ODS & Collaboration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-gemini.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; AI Engineering & LLMs; WebDAV, ODS & Collaboration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-grok4-2m-reasoning.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-developer-journey-grok4-2m.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-system-functions-or-agents-apis-oauth-developer-journey-gemini.html', 'OPAL & Agentic AI; Analytics, Data Engineering & ERA; WebDAV, ODS & Collaboration; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/opal-widget-architecture.drawio.html', 'OPAL & Agentic AI; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/openai-agents-sdk-next-evolution-infographic.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/openai-jobs-analysis-report-2.html', 'AI Engineering & LLMs; Semantic Web, RDF & Ontologies; OPAL & Agentic AI; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/openai-privacy-filter-infographic.html', 'Identity, Security & Privacy; AI Engineering & LLMs; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/openapi-docs-from-yaml-gemini.html', 'Virtuoso Platform; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/openlink-strategy-infographic-gemini-1.html', 'Data Virtualization & Integration; AI Engineering & LLMs; OPAL & Agentic AI; Virtuoso Platform; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/oracle-hr-kg-verification.html', 'Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/polyglot-architect-2.html', 'Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; Data Virtualization & Integration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/polyglot-architect.html', 'Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; Data Virtualization & Integration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/postgres_postgres_jdbc_mt_codex_company_dashboard.html', 'Database, SQL & PostgreSQL; Semantic Web, RDF & Ontologies; Data Virtualization & Integration; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/postgres_postgres_jdbc_mt_codex_linked_data_infographic.html', 'Database, SQL & PostgreSQL; Data Virtualization & Integration; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/pyodbc-mcp-infographic-gemini.html', 'Data Virtualization & Integration; AI Engineering & LLMs; Database, SQL & PostgreSQL; Virtuoso Platform; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/query-visualizer.html', 'SPARQL & Querying; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; DBpedia & Public Data Spaces');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/rdf-file-visualizer-and-query-builder-gemini.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; SPARQL & Querying');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/rdf-linked-data-views-sqlserver.html', 'Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Database, SQL & PostgreSQL; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/rdf-statisical-cude-gemini-1.html', 'Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; SPARQL & Querying; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/relations-rdfviews-virtuoso-1.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; Database, SQL & PostgreSQL');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/reverse-information-paradox-claude_sonnet_5-1.html', 'Semantic Web, RDF & Ontologies; Identity, Security & Privacy; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/reviving-file-save-create-presentation.html', 'WebDAV, ODS & Collaboration; Knowledge Graphs & Linked Data; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/reviving-file-save-create.html', 'WebDAV, ODS & Collaboration; AI Engineering & LLMs; Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/s3-files-infographic.html', 'Cloud Storage & S3; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/scoble-post-on-learning-pyramid-gemini.html', 'Analytics, Data Engineering & ERA; AI Engineering & LLMs; Semantic Web, RDF & Ontologies; OPAL & Agentic AI');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/semantic-web-arrived-infographic.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; AI Engineering & LLMs; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/services-the-new-software-infographic.html', 'Analytics, Data Engineering & ERA; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/small-model-squeeze.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; Identity, Security & Privacy');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/sparqlworks-old.html', 'SPARQL & Querying; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; DBpedia & Public Data Spaces');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/sparqlworks-qa.html', 'SPARQL & Querying; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; DBpedia & Public Data Spaces');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/sparqlworks-skin-test.html', 'SPARQL & Querying; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; DBpedia & Public Data Spaces');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/sparqlworks.html', 'SPARQL & Querying; Semantic Web, RDF & Ontologies; Analytics, Data Engineering & ERA; DBpedia & Public Data Spaces');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/tech-cul-de-sac-via-slogan-first-tech-gemini.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; OPAL & Agentic AI; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/things-you-can-only-do-with-virtuoso.html', 'Virtuoso Platform; Knowledge Graphs & Linked Data; Data Virtualization & Integration; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/unix-mindset-pipes-mcp.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; Presentation, Infographic & Visual Explanation; Data Virtualization & Integration');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/vibe-coding-scales-gemini.html', 'AI Engineering & LLMs; Analytics, Data Engineering & ERA; Identity, Security & Privacy; Cloud Storage & S3');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-08-03-3335-ai-release-claude_sonnet_4_6-1.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Virtuoso Platform; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-benefits-simple-claude-2.html', 'OPAL & Agentic AI; Virtuoso Platform; AI Engineering & LLMs; Cloud Storage & S3');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-benefits-simple-claude.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Database, SQL & PostgreSQL; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-benefits-simple-gemini-2.html', 'Virtuoso Platform; OPAL & Agentic AI; Knowledge Graphs & Linked Data; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-benefits-simple-gemini.html', 'Virtuoso Platform; Database, SQL & PostgreSQL; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-benefits-simple-gpt.html', 'Virtuoso Platform; Database, SQL & PostgreSQL; OPAL & Agentic AI; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-benefits-simple.html', 'Virtuoso Platform; Data Virtualization & Integration; Database, SQL & PostgreSQL; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-offers-claude.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; Database, SQL & PostgreSQL; Virtuoso Platform');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-offers-gemini.html', 'Database, SQL & PostgreSQL; Virtuoso Platform; Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-opal-enterprise-harmonization-infographic-3.html', 'AI Engineering & LLMs; OPAL & Agentic AI; Virtuoso Platform; Semantic Web, RDF & Ontologies; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-rdf-views.html', 'Semantic Web, RDF & Ontologies; Database, SQL & PostgreSQL; Virtuoso Platform; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-turning-data-into-action.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; Database, SQL & PostgreSQL; Presentation, Infographic & Visual Explanation');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-turning-data-into-decisive-knowledge-claude-gemini-fixed.html', 'Presentation, Infographic & Visual Explanation; Database, SQL & PostgreSQL; Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-turning-data-into-decisive-knowledge-claude.html', 'Database, SQL & PostgreSQL; Identity, Security & Privacy; Semantic Web, RDF & Ontologies; AI Engineering & LLMs');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/virtuoso-turning-data-into-decisive-knowledge.html', 'Knowledge Graphs & Linked Data; Presentation, Infographic & Visual Explanation; Semantic Web, RDF & Ontologies; Database, SQL & PostgreSQL');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/wordlift-agents-and-structured-data-claude.html', 'OPAL & Agentic AI; AI Engineering & LLMs; Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/writing-llms-knowledge-graphs-claude.html', 'Semantic Web, RDF & Ontologies; Knowledge Graphs & Linked Data; AI Engineering & LLMs; Analytics, Data Engineering & ERA');
INSERT INTO DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE (PATH, CATEGORY) VALUES ('/DAV/www2.openlinksw.com/data/html/writing-llms-knowledge-graphs-gemini.html', 'Knowledge Graphs & Linked Data; Semantic Web, RDF & Ontologies; AI Engineering & LLMs; OPAL & Agentic AI');

CREATE PROCEDURE DB.DBA.APPLY_OPENLINK_HTML_SCHEMA_CATEGORY ()
{
  DECLARE _path VARCHAR;
  DECLARE _category LONG VARCHAR;
  DECLARE _dav_user VARCHAR;
  DECLARE _pwd VARCHAR;
  DECLARE _rc ANY;
  DECLARE _ok INTEGER;
  DECLARE _failed INTEGER;

  _ok := 0;
  _failed := 0;
  _dav_user := 'dba';
  _pwd := (SELECT pwd_magic_calc (U_NAME, U_PASSWORD, 1) FROM DB.DBA.SYS_USERS WHERE U_NAME = _dav_user);

  FOR SELECT PATH, CATEGORY FROM DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE DO
  {
    _path := PATH;
    _category := CATEGORY;
    _rc := DB.DBA.DAV_PROP_SET (_path, 'schema:category', _category, _dav_user, _pwd, 1);
    IF (DB.DBA.DAV_HIDE_ERROR (_rc) IS NULL)
      _failed := _failed + 1;
    ELSE
      _ok := _ok + 1;
  }

  RESULT_NAMES (event, ok_count, failed_count);
  RESULT ('schema:category apply complete', _ok, _failed);
}
;

DB.DBA.APPLY_OPENLINK_HTML_SCHEMA_CATEGORY ();

-- Spot-check the first few applied values.
SELECT TOP 10
  s.PATH,
  DB.DBA.DAV_PROP_GET (s.PATH, 'schema:category', 'dba', (SELECT pwd_magic_calc (U_NAME, U_PASSWORD, 1) FROM DB.DBA.SYS_USERS WHERE U_NAME = 'dba')) AS schema_category
FROM DB.DBA.OPENLINK_HTML_DAV_CATEGORY_STAGE s
ORDER BY s.PATH;

DROP PROCEDURE DB.DBA.APPLY_OPENLINK_HTML_SCHEMA_CATEGORY;

