#!/usr/bin/env python3
"""Sanity-check a weblog-from-webdav skill bundle."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


CHECKS = {
    "templates/deploy-weblog-opl-site.sql": [
        "DAV_RES_UPLOAD_STRSES_INT",
        "string_output",
        "RSS",
        "Atom",
    ],
    "templates/deploy-weblog-opl-site-facet.sql": [
        "schema:category",
        "dict_iter_next",
        "contains",
        "._%",
    ],
    "SKILL.md": [
        "isql-engine",
        "webdav-posts",
        "WebDAV is then used for the post-publication workflow",
    ],
    "references/webdav-mode.md": [
        "not the engine setup channel",
        "switch to `isql` engine bootstrap",
    ],
    "references/webdav-weblog-engine-gate.md": [
        "Static HTML is only an optional preview",
        "DAV_RES_UPLOAD_STRSES_INT",
        "validate_generated_weblog_bundle.py",
    ],
    "scripts/validate_generated_weblog_bundle.py": [
        "DAV_RES_UPLOAD_STRSES_INT",
        "string_output",
        "VHOST_DEFINE",
    ],
    "templates/register-weblog-pinning-tool.sql": [
        "WEBLOG_DAV_SET_PIN",
        "schema:position",
        "REGISTER_CHAT_FUNCTION",
        "openapi.yaml",
        "OPAL registration is best-effort",
        "exec ('OAI.DBA.REGISTER_CHAT_FUNCTION",
        "DAV_PROP_SET_INT",
    ],
    "references/opal-tool-mode.md": [
        "WEBLOG_DAV_SET_PIN",
        "REGISTER_CHAT_FUNCTION",
        "openapi.yaml",
        "OPAL registration is best-effort",
    ],
    "templates/deploy-weblog-skinned.sql": [
        "WEBLOG_DAV_DEPLOY_SKINNED",
        "WEBLOG_DAV_GET_COLLECTION_PROP",
        "weblog:skin",
        "weblog:newsletterEnabled",
        "weblog:publicRoute",
        "nl_action",
        "RES_OWNER",
        "admin_route",
        "{{ADMIN_ROUTE}}",
        "admin_msg",
        "dashboard.html",
        "WEBLOG_DASHBOARD_REFRESH",
        "action_route",
        "{{ACTION_ROUTE}}",
        "weblog:actionRoute",
        "action_realm",
        "WEBLOG_ADMIN_AUTH_FN",
        "HP_AUTH_SQL_USER",
        "vsp_auth_vec",
        "auth_fn=>'DB.DBA.WEBLOG_ADMIN_AUTH_FN'",
        "sec=>'digest'",
        "weblog:adminDavUser",
        "on_action_route",
        "weblog:adminCollection",
        "admin_collection",
        "DAV_COL_CREATE_INT",
        "'111111000N'",
        "must be outside the public blog collection",
        "sec=>'SSL'",
        "'URIQA', 'DefaultHost'",
        "'HTTPServer', 'SSLPort'",
        "HP_LISTEN_HOST <> ''",
        "SYS_ROLE_GRANTS",
        "if (lower (trim (uname)) = 'dba') return 1",
        "DAV_PROP_SET_INT (''{{DAV_COLLECTION}}''",
        "email_props",
        "tagline_link_url",
        "tagline_link_text",
        "{{TAGLINE_LINK_HTML}}",
        "post-permalink",
        "WebDAV Permalink",
        "feed-btn subscribe",
        'id="newsletter"',
        "is_https_ctx ()",
        "like ''Host:%''",
        "allow_template_overwrite",
        "multi-skin, config-driven",
        "<dialog id=\"newsletter\"",
        "showModal()",
        "nl-close",
        "update WS.WS.SYS_DAV_RES set RES_PERMS = '111101101R' where RES_FULL_PATH = index_path",
        "set_email_template",
        "et_subject_prop",
        "WEBLOG_CHECK_EMAIL_TEMPLATE_TOKENS",
        "Manual entry failed for",
        "already a confirmed subscriber",
        "admin_action",
        "send_digest_now",
        "set_digest_interval",
        "set_digest_mode",
        "set_content_mode",
        "import_subscribers_csv",
        "import_subscribers_rdf",
        "import_subscribers_manual",
        "set_skin",
        "set_email_config",
        "set_digest_schedule",
        "set_dashboard_schedule",
        "set_post_category",
        "set_post_pin",
        "admin_unsubscribe",
        "admin_email",
        "weblog:adminEmail",
        "nl_is_post",
        "nl_needs_confirm_post",
    ],
    "templates/register-weblog-newsletter.sql": [
        "WEBLOG_NEWSLETTER_SUBSCRIBE",
        "WEBLOG_NEWSLETTER_CONFIRM",
        "WEBLOG_NEWSLETTER_UNSUBSCRIBE",
        "WEBLOG_NEWSLETTER_SEND_DIGEST",
        "WEBLOG_NEWSLETTER_POST_TITLE",
        "WEBLOG_NEWSLETTER_POST_EXCERPT",
        "WEBLOG_NEWSLETTER_POST_CARD",
        "WEBLOG_NEWSLETTER_HTML_SHELL",
        "WEBLOG_NEWSLETTER_IS_INFOGRAPHIC",
        "WEBLOG_NEWSLETTER_STRIP_ELEMENT",
        "WEBLOG_NEWSLETTER_EXTRACT_STYLE_BLOCKS",
        "extra_css",
        "anim-fade",
        "ui-monospace",
        "Email Server Config",
        "Tagging &amp; Scheduling",
        "weblog-dashboard-refresh",
        "data-theme-toggle",
        "theme-switch-thumb",
        "role=\"switch\"",
        "weblog-dashboard-theme",
        "category-options",
        "row-action",
        "admin-banner-slot",
        "admin_msg",
        "WEBLOG_NEWSLETTER_IMPORT_CSV",
        "WEBLOG_NEWSLETTER_IMPORT_RDF",
        "WEBLOG_NEWSLETTER_IMPORT_ONE",
        "WEBLOG_NEWSLETTER_SEND_ACTIVATION",
        "WEBLOG_NEWSLETTER_SEND_UNSUBSCRIBE_NOTICE",
        "WEBLOG_NEWSLETTER_BULK_HEADERS",
        "WEBLOG_NEWSLETTER_NOTIFY_ADMIN",
        "weblog:adminEmail",
        "Reply-To",
        "Message-ID",
        "List-Id",
        "List-Unsubscribe",
        "List-Unsubscribe-Post",
        "Precedence: bulk",
        "WS_NAME",
        "manual-add",
        "skin_choice",
        "weblog:newsletterContentMode",
        "smtp_send",
        "WEBLOG_SUBSCRIBER",
        "WEBLOG_DASHBOARD_REFRESH",
        "WEBLOG_DASHBOARD_SCHEDULE_REFRESH",
        "WEBLOG_NEWSLETTER_TRY_DASHBOARD_REFRESH",
        "details.collapsible",
        "summary.panel-h2",
        "summary.panel-h3",
        "count-badge",
        "WEBLOG_RENDER_EMAIL_TEMPLATE",
        "WEBLOG_CHECK_EMAIL_TEMPLATE_TOKENS",
        "weblog:emailSubjectConfirm",
        "weblog:emailBodyConfirm",
        "weblog:emailSubjectDigest",
        "weblog:emailIntroDigest",
        "weblog:emailSubjectImmediate",
        "weblog:emailSubjectActivation",
        "weblog:emailBodyActivation",
        "weblog:emailSubjectUnsubscribeNotice",
        "weblog:emailBodyUnsubscribeNotice",
        "weblog:emailSubjectAdminAlert",
        "weblog:adminDavUser",
        "weblog:newsletterMode",
        "immediate",
        "text/html; charset=UTF-8",
        "action_route",
        "weblog:actionRoute",
        "weblog:adminCollection",
        "admin_coll || 'dashboard.html'",
        "'110110000N'",
        "operator_gid",
        "admin_owner_uid",
        "email := lower (trim (email))",
    ],
    "references/skin-authoring-contract.md": [
        "Resolution order",
        "weblog:skin",
        "PROP_TYPE='C'",
    ],
    "templates/upgrade.sql": [
        "SECTION 1 of 2",
        "SECTION 2 of 2",
        "REDEPLOY",
        "WEBLOG_DAV_DEPLOY_SKINNED",
        "TMP_WEBLOG_UPGRADE_APPLY",
        "TMP_WEBLOG_UPGRADE_AUTODETECT",
        "TMP_WEBLOG_UPGRADE_GRANT_ROLE",
        "WEBLOG_OPERATOR",
        "PRE-FLIGHT BACKUP 1 of 2",
        "PRE-FLIGHT BACKUP 2 of 2",
        "WEBLOG_SUBSCRIBER_BACKUP_",
        "WEBLOG_UPGRADE_BACKUP",
        "TO RESTORE",
        "TMP_WEBLOG_UPGRADE_RESTORE_SUBSCRIBERS",
    ],
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skill-dir", type=Path, default=Path(__file__).resolve().parents[1])
    args = parser.parse_args()
    missing: list[str] = []
    for rel, needles in CHECKS.items():
        path = args.skill_dir / rel
        if not path.exists():
            missing.append(f"missing file: {rel}")
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        for needle in needles:
            if needle not in text:
                missing.append(f"{rel}: missing marker {needle!r}")
    if missing:
        for item in missing:
            print(item, file=sys.stderr)
        return 1
    print("weblog-from-webdav bundle markers OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
